// The plates as designed: stations (km, tracks) and trains (route, speed in
// km/h, ready and due minutes, minimum call). emit.mjs turns this into
// src/Levels.elm. Speeds: express 60, stopping 40, goods 30.
const E = 60, L = 40, G = 30;
const st = (name, km, tracks = 2) => ({ name, km, tracks });
const tr = (name, ink, from, to, speed, ready, due, call = 0) => ({ name, ink, from, to, speed, ready, due, call });
const hm = (h, m) => h * 60 + m;
export const levels = [
  { id: 1, title: 'First Meeting', clock: hm(6, 0), span: 40,
    brief: 'Two trains, one track. They can pass only at Brill, where the line has a loop. Drag the Down local’s knob at Brill to make it wait there until the Up local arrives.',
    stations: [st('Ashby', 0, 3), st('Brill', 6), st('Colley', 12, 3)],
    trains: [tr('Down local', 0, 0, 2, L, 0, 30), tr('Up local', 1, 2, 0, L, 3, 30)] },
  { id: 2, title: 'Choose the Loop', clock: hm(6, 30), span: 60,
    brief: 'Two loops this time, and the express must not be late. Where should the trains meet?',
    stations: [st('Wenlow', 0, 3), st('Ferriby', 8), st('Mardle', 14), st('Hobb End', 20, 3)],
    trains: [tr('Down express', 2, 0, 3, E, 0, 24), tr('Up goods', 3, 3, 0, G, 0, 44)] },
  { id: 3, title: 'A Halt Is Not a Loop', clock: hm(7, 0), span: 50,
    brief: 'Stoke is a halt with a single track: a train may stop there, but two trains cannot pass. Find somewhere else for them to meet.',
    stations: [st('Pellham', 0, 3), st('Stoke', 6, 1), st('Quarley', 10), st('Ridgeway', 16, 3)],
    trains: [tr('Down local', 0, 0, 3, L, 0, 30), tr('Up local', 1, 3, 0, L, 0, 30)] },
  { id: 4, title: 'Stand Aside', clock: hm(5, 40), span: 60,
    brief: 'A fast train behind a slow one. Trains can overtake only at a loop, so the goods must step aside at Upcott and let the express by.',
    stations: [st('Tamsey', 0, 3), st('Upcott', 8), st('Vane', 16, 3)],
    trains: [tr('Down goods', 3, 0, 2, G, 0, 49), tr('Down express', 2, 0, 2, E, 10, 36)] },
  { id: 5, title: 'Three’s Company', clock: hm(8, 0), span: 70,
    brief: 'Three trains now. The express has the tightest deadline; the goods has time to spare.',
    stations: [st('Allerby', 0, 3), st('Birkett', 6), st('Carrow', 12), st('Dunster', 18, 3)],
    trains: [tr('Down local', 0, 0, 3, L, 0, 40), tr('Down goods', 3, 0, 3, G, 5, 60), tr('Up express', 2, 3, 0, E, 0, 30)] },
  { id: 7, title: 'Two Tracks Only', clock: hm(10, 20), span: 80,
    brief: 'A loop has two tracks, so three trains cannot stand at Kestle at once. Stagger them.',
    stations: [st('Jessop', 0, 3), st('Kestle', 6), st('Lanyon', 18, 3)],
    trains: [tr('Down express', 2, 0, 2, E, 0, 45), tr('Down local', 0, 0, 2, L, 6, 70), tr('Up goods', 3, 2, 0, G, 0, 60)] },
  { id: 8, title: 'Calling at All Stations', clock: hm(11, 0), span: 80,
    brief: 'The local must stop for at least two minutes at every station, halts included. Keep the express on time behind it.',
    stations: [st('Marston', 0, 3), st('Nethy', 4, 1), st('Orford', 9), st('Pinner', 13, 1), st('Quenby', 18, 3)],
    trains: [tr('Down local', 0, 0, 4, L, 0, 50, 2), tr('Down express', 2, 0, 4, E, 10, 40), tr('Up goods', 3, 4, 0, G, 0, 70)] },
  { id: 6, title: 'Short Workings', clock: hm(9, 0), span: 80,
    brief: 'Not every train runs the whole line. The two shuttles work only between Gathorne and Ivymead.',
    stations: [st('Eldon', 0, 3), st('Fenwick', 5), st('Gathorne', 10, 3), st('Holloway', 16), st('Ivymead', 22, 3)],
    trains: [tr('Down express', 2, 0, 4, E, 10, 45), tr('Up goods', 3, 4, 0, G, 0, 60), tr('Down shuttle', 1, 2, 4, L, 0, 30), tr('Up shuttle', 5, 4, 2, L, 25, 60)] },
  { id: 9, title: 'Morning Rush', clock: hm(6, 0), span: 90,
    brief: 'Two expresses, a goods and a local, all before breakfast.',
    stations: [st('Redmire', 0, 3), st('Saltley', 6), st('Thorne', 12), st('Ulcombe', 18), st('Vardy', 24, 3)],
    trains: [tr('Down express', 2, 0, 4, E, 5, 40), tr('Down goods', 3, 0, 4, G, 0, 75), tr('Up local', 0, 4, 0, L, 0, 60), tr('Up express', 1, 4, 0, E, 20, 60)] },
  { id: 10, title: 'Market Day', clock: hm(7, 30), span: 100,
    brief: 'The locals call for a minute everywhere, and Zeal is only a halt.',
    stations: [st('Wymond', 0, 3), st('Yarrow', 5), st('Zeal', 9, 1), st('Abbots', 14), st('Brampton', 20), st('Cresswell', 26, 3)],
    trains: [tr('Down local', 0, 0, 5, L, 0, 70, 1), tr('Down express', 2, 0, 5, E, 15, 55), tr('Up goods', 3, 5, 0, G, 0, 90), tr('Up local', 1, 5, 0, L, 20, 85, 1)] },
  { id: 11, title: 'The Branch Goods', clock: hm(13, 0), span: 100,
    brief: 'Two goods trains finish in the yard at Fold, and a shuttle starts from there. Two expresses need the whole line.',
    stations: [st('Dallow', 0, 3), st('Easby', 6), st('Fold', 11, 3), st('Garth', 15, 1), st('Hexley', 20), st('Ingram', 26, 3)],
    trains: [tr('Down express', 2, 0, 5, E, 10, 50), tr('Up express', 1, 5, 0, E, 10, 50), tr('Down goods', 3, 0, 2, G, 0, 40), tr('Up goods', 4, 5, 2, G, 0, 60), tr('Shuttle', 0, 2, 5, L, 20, 70)] },
  { id: 12, title: 'The Night Mail', clock: hm(22, 10), span: 120,
    brief: 'The mail waits for no one, and the up express is close behind it. Everything else must fit around them.',
    stations: [st('Kirby', 0, 3), st('Langley', 6), st('Morrow', 12), st('Nabb', 16, 1), st('Oakle', 21), st('Pendle', 27, 3)],
    trains: [tr('Down mail', 2, 0, 5, E, 20, 52), tr('Down goods', 3, 0, 5, G, 0, 88), tr('Up local', 0, 5, 0, L, 0, 54, 1), tr('Up goods', 4, 5, 0, G, 15, 118), tr('Up express', 1, 5, 0, E, 40, 70)] },
  { id: 13, title: 'The Grand Chart', clock: hm(5, 0), span: 130,
    brief: 'The whole Ashby line at once: six trains, seven stations. Take your time.',
    stations: [st('Ashby', 0, 3), st('Brill', 5), st('Colley', 11), st('Dunmore', 15, 1), st('Eskdale', 20), st('Farthing', 26), st('Gorsedene', 32, 3)],
    trains: [tr('Down express', 2, 0, 6, E, 10, 57), tr('Down local', 0, 0, 6, L, 0, 92, 1), tr('Down goods', 3, 0, 6, G, 20, 112), tr('Up express', 1, 6, 0, E, 30, 74), tr('Up local', 5, 6, 0, L, 0, 62, 1), tr('Up goods', 4, 6, 0, G, 5, 122)] },
];
levels.forEach((l, i) => { l.id = i + 1; });
