// The par search and the par proof run on rules.mjs, a JavaScript mirror of
// the Elm rules in src/Rail.elm. This writes tests/MirrorCases.elm: for every
// plate, random timetables plus its par solution nudged a minute or two either
// way (where touching times and full loops are decided), each with the
// verdict the mirror gives (conflicts by kind and trains, late trains,
// waiting). The Elm test MirrorTests checks that src/Rail.elm gives the same
// verdict for every one. With --check, compare instead of writing (used by
// the tests).
//   node tools/par-search/mirror.mjs [--check]
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { levels } from './levels.mjs';
import { conflicts, late, waiting } from './rules.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const file = join(here, '..', '..', 'tests', 'MirrorCases.elm');
const results = JSON.parse(readFileSync(join(here, 'results.json'), 'utf8'));
const PER_PLATE = 40;
const NUDGES = 16;

// A fixed-seed generator, so the file is reproducible.
let seed = 20260926;
const random = () => {
  seed = (seed * 1103515245 + 12345) % 2147483648;
  return seed / 2147483648;
};
// Many zeros (trains running as early as they can) and some long waits.
const extra = (max) => (random() < 0.4 ? 0 : Math.floor(random() * max));

// The par solution with one knob moved by -2..+2 minutes (kept in bounds).
const nudged = (level, plan) => {
  const copy = plan.map((p) => ({ dep: p.dep, dwells: [...p.dwells] }));
  const i = Math.floor(random() * level.trains.length);
  const t = level.trains[i];
  const delta = [-2, -1, 1, 2][Math.floor(random() * 4)];
  const k = Math.floor(random() * (1 + copy[i].dwells.length));
  if (k === 0) copy[i].dep = Math.max(t.ready, copy[i].dep + delta);
  else copy[i].dwells[k - 1] = Math.max(t.call, copy[i].dwells[k - 1] + delta);
  return copy;
};

const kind = { head: 'H', rear: 'R', crowd: 'C' };
const cases = [];
for (const level of levels) {
  const par = results[level.id].plan;
  const plans = [par];
  for (let n = 0; n < NUDGES; n++) plans.push(nudged(level, par));
  for (let n = 0; n < PER_PLATE; n++) {
    plans.push(
      level.trains.map((t) => ({
        dep: t.ready + extra(30),
        dwells: Array.from({ length: Math.abs(t.to - t.from) - 1 }, () => t.call + extra(15)),
      })),
    );
  }
  for (const plan of plans) {
    const found = conflicts(level, plan)
      .map((c) => kind[c.kind] + c.trains.slice().sort((a, b) => a - b).join(''))
      .sort();
    const verdict = `${found.join(',')}|${late(level, plan).join(',')}|${waiting(level, plan)}`;
    cases.push(`( ${level.id}, [ ${plan.map((p) => `[ ${[p.dep, ...p.dwells].join(', ')} ]`).join(', ')} ], ${JSON.stringify(verdict)} )`);
  }
}

const elm = `module MirrorCases exposing (cases)

{-| Generated by tools/par-search/mirror.mjs; do not edit. For every plate,
its par solution, that solution nudged a minute or two, and random
timetables, each with the verdict of the JavaScript mirror of the rules:
"conflicts|late trains|waiting", conflicts as a kind (H head-on, R rear-end,
C crowded) and the trains involved, sorted.
-}


cases : List ( Int, List (List Int), String )
cases =
    [ ${cases.join('\n    , ')}
    ]
`;

if (process.argv.includes('--check')) {
  if (readFileSync(file, 'utf8') !== elm) {
    console.error('tests/MirrorCases.elm is out of date: run node tools/par-search/mirror.mjs');
    process.exit(1);
  }
} else {
  writeFileSync(file, elm);
  console.log(`wrote ${cases.length} cases to tests/MirrorCases.elm`);
}
